version: '3.9'
services:
  ntp_server:
    build: ntp_server
    hostname: ntp-server
    container_name: ntp-server
    environment:
      UDP_IP_ADDRESS: "0.0.0.0"
      UDP_PORT_NO: 1234
    ports:
      - "1234:1234/udp"